### ISSUE TITLE
Use case over react-stonecutter?

### ISSUE THREAD

**Issue by ms88privat** [tsuyoshiwada/react-stack-grid#11]
You mentioned [react-stonecutter](https://github.com/dantrain/react-stonecutter) in your readme. Right now I'm in the beginning of evaluating a lot of react lists and grids and I can't really tell where the difference is between your project and stonecutter. Could you please help me out here and maybe describe it in the readme more clearly?

Is it about the placeholder thing? Thank you very much

**Comment by tsuyoshiwada** [comment]
Hi @ms88privat. Thanks for Issues.

Not all of the differences are enumerated, but there are something very different in the following.

* Percentage support for `columnWidth`.
* Support appear animation.
* Support for css autoprefix. (use `inline-style-prefixer`)
* `columns` is not necessary, it is automatically calculated from the width of the parent.

Thanks.

**Comment by ms88privat** [comment]
Thanks, that helps!

**Comment by tsuyoshiwada** [comment]
You are welcome !
