### ISSUE TITLE
PropTypes warning

### ISSUE THREAD

**Issue by allencoded** [tsuyoshiwada/react-stack-grid#12]
It seems that react deprecated the way this package uses PropTypes. 

Consumers above React version 15.5 get the following warning:
`
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Included is the link from the react documents about its deprecation and replacement.
https://facebook.github.io/react/warnings/dont-call-proptypes.html

Otherwise this project is exactly what I have been looking for. Great work.

**Comment by tsuyoshiwada** [comment]
Hi @allencoded, Thanks you for Issues.

I will fix the prop-types warning this week :+1:
We apologize for the inconvenience but please wait a moment :pray:

**Comment by tsuyoshiwada** [comment]
Hi @allencoded, Released a fix version of PropTypes warning :tada: ([react-stack-grid@0.2.1](https://www.npmjs.com/package/react-stack-grid))
Please check them when you have the time.
