### ISSUE TITLE
Migrate from react-addons-transition-group to react-transition-group

### ISSUE THREAD

**Issue by mquandalle** [tsuyoshiwada/react-stack-grid#17]
NPM/Yarn emits the following warning when installing `react-stack-grid`:

> warning react-stack-grid > react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead.

This is documented [here](https://facebook.github.io/react/docs/animation.html).

**Comment by tsuyoshiwada** [comment]
Hi, Thanks for Issues :smiley:
I'd like to switch to `react-transition-group` and release it :+1:

**Comment by tsuyoshiwada** [comment]
Hi @mquandalle.
Thank you. Migrated with the release of `0.2.3`.
