### ISSUE TITLE
Callback after layout

### ISSUE THREAD

**Issue by jarib** [tsuyoshiwada/react-stack-grid#22]
Would be great to be able to pass an `onLayout` prop to get notified after a layout update.

```javascript
<StackGrid onLayout={::this.handleLayout} ... />
```

**Comment by tsuyoshiwada** [comment]
Hi @jarib, Thanks for issues !

It's nice idea.
I think I will start working on weekends.

If possible send me a PR I am more glad!

**Comment by tsuyoshiwada** [comment]
Hi @jarib.
Release version 0.4.0 which supports `onLayout` props :tada:
Please check when you have time.
