### ISSUE TITLE
select multiply items & select with drag mouse area

### ISSUE THREAD

**Issue by rihannarickeminem** [tsuyoshiwada/react-stack-grid#24]
is there any solutions ,  or something nearest implemented? Something like `http://valerybugakov.github.io/react-selectable-fast/` or `http://pablofierro.github.io/react-drag-select/` to omplement with this great library

**Comment by tsuyoshiwada** [comment]
Hi @rihannarickeminem, Thanks for Issue.

Implementation for selection is not included in `react-stack-grid`.
You need to implement your own it :+1:

Although it will be a while ago, there are repositories that implemented the selection UI so please try it :smiley:

* [DEMO](https://tsuyoshiwada.github.io/react-selectable-sandbox/)
* [Source Code](https://github.com/tsuyoshiwada/react-selectable-sandbox)

In the above sample we implement it using [react-selectable](https://github.com/unclecheese/react-selectable).
