### ISSUE TITLE
will it support horizontal grid?

### ISSUE THREAD

**Issue by wuzhuzhu** [tsuyoshiwada/react-stack-grid#25]
Thanks for your awesome work.
Is there any chance to add horizontal flow into option?

**Comment by tsuyoshiwada** [comment]
Hi @wuzhuzhu, Sorry late reply :cry:
There is no plan to add a horizontal flow. However, PR is always welcome :muscle:

**Comment by tsuyoshiwada** [comment]
@wuzhuzhu Released as v0.5.0 :tada:

**Comment by wuzhuzhu** [comment]
wow cool！
