### ISSUE TITLE
export * as easings leads to unexpected token error

### ISSUE THREAD

**Issue by nerdess** [tsuyoshiwada/react-stack-grid#41]
i like to run the jsx-code of your plugin to be able to change it a bit.

but when i try to do this i get an "unexpected token" error, you can see it here: https://postimg.org/image/ppgts6rk5/

i understand that writing e.g.

`export * as easings`

is something that is not supported yet (but might come in ES7). 

so i tried to get it to work using this babel-plugin but still no success: http://babeljs.io/docs/plugins/transform-export-extensions/

this  is my .babelrc

`{
  "presets": [
    "flow",
    "es2015",
    "react",
    "stage-1"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "transform-export-extensions"
  ]
}
`
any help would be appreciated!

**Comment by nerdess** [comment]
ok ended up rewriting the "export * as" statements into e.g.

`import* as easings from './animations/easings';
export {easings};` 

also had to add the comment

` /* eslint-disable import/first */` 

still though, a working solution with your code would be much nicer :)

**Comment by wadackel** [comment]
Hi @nerdess, I am sorry for the delay in my response :cry:

I think that the problem reported is not a problem of 'reaction stack lattice' :hand:
I would like to close this Issues.

we are waiting for a report if there are other problems :smiley:
