### ISSUE TITLE
How to force items position recalculation for column?

### ISSUE THREAD

**Issue by ORuban** [tsuyoshiwada/react-stack-grid#5]
Let's say my custom `GridItem` component has 2 visual states: normal and extended. Extended means that height of GridItem is 200% from normal. 

By default, all items have the normal states, but on `click` event the item is extended. The problem is that right now item's positions are not recalculated in the column and so I have items overlapping.

**Comment by tsuyoshiwada** [comment]
Hi @ORuban. Thanks for issues.

In the next hack, animation will be executed for a moment but you can forcibly recalculate the layout.

---

### Screenshot

![demo-gfm](https://cloud.githubusercontent.com/assets/5393238/23716903/30443fda-0475-11e7-9387-56523153c57c.gif)
### Sample code

```javascript
class App extends Component {
  state = {
    items: [
      { active: false, id: 1, text: 'Sample 1' },
      { active: false, id: 2, text: 'Sample 2' },
      // more items ...
    ]
  };

  render() {
    const { items } = this.state;

    return (
      <StackGrid
        columnWidth={150}
      >
        {items.map(({ id, text, active }) =>
          <div
            key={active ? `active-${id}` : id}
            style={{
              background: '#555',
              color: '#fff',
              height: active ? 400 : 200,
            }}
            onClick={() => {
              this.setState({
                items: items.map(o => ({
                  ...o,
                  active: o.id === id ? !o.active : o.active,
                })),
              });
            }}
          >
            {text}
          </div>
        )}
      </StackGrid>
    );
  }
}
```

It forcibly performs rendering by changing the key property depending on the state.
